print("Hello world!")
print([23232,23,23,232,0,232,3])
print({"name":"John", "age":30, "city":"New York"})
print(("apple", "banana", "cherry"))
print(3.14159)
print(True)
print(None)
print(f"Formatted number: {12345.6789:.2f}")
print("Special characters: \n\tNew line and tab")
print("Unicode characters: 😊, 🚀, 🌍")
print("Escape sequences: \"Double quotes\", \'Single quotes\', \\Backslash\\")
print("Multiline string:\nThis is line one.\nThis is line two.")
print("Raw string: C:\\Users\\Name\\Documents")
print("Concatenated string: " + "Hello, " + "world!")
print("Repeated string: " * 3)
print("Length of string 'Hello':", len("Hello"))
print("Sum of numbers 1 to 5:", sum(range(1, 6)))
print("Max of numbers 10, 20, 30:", max(10, 20, 30))
print("Min of numbers 10, 20, 30:", min(10, 20, 30))
print("Hello",23.232,2/3,3j,{"name":"John"})
print("Pi rounded to 3 decimal places:", round(3.14159, 3),sep=' | ')
print("This", "is", "a", "test", sep=" - ")
print("No newline at the end\n next line", sep="-----")
print("Custom end character", end=" *** ")
print("Next print statement starts here.",end="")
print(" This is on the same line.")
# Writing to a file using print()
with open("Basic/STDOUT/myfile.txt", "w") as file:
    print("Mixing", 42, 3.14, True, None, [1, 2, 3], sep=" | ", end=" <<< END >>>\n", file=file)